name: 'CI'

on:
  push:
    branches:
    - main
    - features/**
    tags:
    - '*.*.*'
  pull_request:

env:
  DOTNET_NOLOGO: true
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/itpro-devops/_packaging/ITPRO/nuget/v3/index.json
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  DOTNET_VERSION: '3.1.x' 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
            source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
          env:
            NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }} 
    - run: dotnet --info
    
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - if: matrix.runs-on == 'windows-latest' && github.ref != 'refs/heads/main' && !contains(github.ref, 'refs/tags/')
      run: ./build.ps1
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      run: |
        ./build.ps1
        dotnet nuget push .\nuget\*.nupkg -k az